### ISSUE TITLE
Got error in Colab Pro high men

### ISSUE THREAD

**Issue by Semonxue** [camenduru/I2VGen-XL-colab#2]
Thank you Camendurn, great work for make it done on colab.
I run this 2-3 times in 2 hours, the latest version is still not work.

```
...
2023-08-24 12:53:07,688 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/Video-to-Video
2023-08-24 12:53:07,689 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/Video-to-Video.
2023-08-24 12:53:07,692 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/Video-to-Video
2023-08-24 12:53:35,306 - modelscope - INFO - Build encoder with FrozenOpenCLIPEmbedder
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, group_key, default_args)
    209         if hasattr(obj_cls, '_instantiate'):
--> 210             return obj_cls._instantiate(**args)
    211         else:

20 frames
OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.75 GiB total capacity; 13.76 GiB already allocated; 60.81 MiB free; 14.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

OutOfMemoryError                          Traceback (most recent call last)
OutOfMemoryError: VideoToVideo: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.75 GiB total capacity; 13.76 GiB already allocated; 60.81 MiB free; 14.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

OutOfMemoryError                          Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, group_key, default_args)
    213     except Exception as e:
    214         # Normal TypeError does not print class name.
--> 215         raise type(e)(f'{obj_cls.__name__}: {e}')

OutOfMemoryError: VideoToVideoPipeline: VideoToVideo: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.75 GiB total capacity; 13.76 GiB already allocated; 60.81 MiB free; 14.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
![image](https://github.com/camenduru/I2VGen-XL-colab/assets/372518/518292db-5e62-40c3-865c-68d5b10ea6a3)

**Comment by camenduru** [comment]
We tested the latest version, and it is working  🥳 Are you on community discord?

**Comment by camenduru** [comment]
we need A100

**Comment by Semonxue** [comment]
> we need A100

I tried A100,the GPU MEM is not enough. I'm waiting the A100 high Men available .

**Comment by Semonxue** [comment]
I'm trying on runpod.

**Comment by Semonxue** [comment]
I got error in runpod:
server info:  1 x RTX A4500 , 12 vCPU 62 GB RAM

```
NameError                                 Traceback (most recent call last)
Cell In[2], line 152
    149     image_submit.click(fn=image_to_video, inputs=[image_in], outputs=[video_out_1])
    150     video_submit.click(fn=video_to_video, inputs=[video_out_1, text_in], outputs=[video_out_2])
--> 152 demo.queue(max_size=10).launch(share=True)

NameError: name 'demo' is not defined
```

**Comment by camenduru** [comment]
yep we fixed this bug

**Comment by camenduru** [comment]
please use the latest code

**Comment by Semonxue** [comment]
> please use the latest code

It can run on runpod but any generate will reach mem limit.
![image](https://github.com/camenduru/I2VGen-XL-colab/assets/372518/c10cddb5-158d-452d-8c96-fd5686eeeea2)
GPU is used up.
![image](https://github.com/camenduru/I2VGen-XL-colab/assets/372518/291ffadc-5a2f-419e-b003-70b9d5acd836)

**Comment by camenduru** [comment]
we need 34GB VRAM
![image](https://github.com/camenduru/I2VGen-XL-colab/assets/54370274/0afc6b25-1132-4340-aa30-d746a88c6979)

**Comment by Semonxue** [comment]
it works on a 48G VRAM runpod server
![image](https://github.com/camenduru/I2VGen-XL-colab/assets/372518/b49fa032-7646-455e-bd20-0824cc2e4dcc)
